version: "3.0"

services:
  db:
    image: postgres:15-bookworm
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=natura
    ports:
      - "5435:5432"
    volumes:
      - db-natura:/var/lib/postgresql/data

volumes:
  db-natura:
  